services:
  - type: web
    name: alef-radar
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --include=dev && ([ -f node_modules/@rolldown/binding-linux-x64-gnu/rolldown-binding.linux-x64-gnu.node ] || npm i @rolldown/binding-linux-x64-gnu@1.2.12 --force) && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
